# Use postgres/example user/password credentials
version: '3.1'

volumes:
  db-data: { }

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./tools/psql/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080